### ISSUE TITLE
Fix missing icons/backgrounds

### ISSUE THREAD

**Issue by linclark** [firefox-devtools/original-console-fork#271]
The warning/error icons and backgrounds went missing. I have a feeling this relates to #225

**Comment by linclark** [comment]
So at least one of the issues is that we used to have an `exception` category, but when we switched to Chrome RDP that became `javascript`. This has an impact because when we are styling based on level, we are applying different styles based on category as well. 

For example:

``` css
.message[category=exception][severity=error] > .icon::before,
.message.exception.error > .icon::before {
  background-position: -12px -24px;
}

...

.message[category=console][severity=error] > .icon::before,
.message[category=output][severity=error] > .icon::before,
.message[category=server][severity=error] > .icon::before,
.message.console-api.error > .icon::before,
.message.output.error > .icon::before,
.message.server.error > .icon::before {
  background-position: -12px -36px;
}
```

@bgrins do you think we can simplify the rules and just apply one set of rules each for `.error`, `.warn`, etc?
